[package]
name = "physis"
version = "0.1.0"
authors = ["Joshua Goins <josh@redstrate.com>"]
edition = "2021"
description = "Interact with XIV game data."
license = "GPL-3.0"
homepage = "https://xiv.zone/physis"
repository = "https://git.sr.ht/~redstrate/physis"
keywords = ["ffxiv", "modding"]
categories = ["parsing"]

[[bench]]
name = "physis_benchmark"
harness = false

[dev-dependencies]
# criterion is not updated to 0.4 yet, which removes an unmaintained package
criterion = { git = "https://github.com/bheisler/criterion.rs", branch="version-0.4", version="0.3.5" }

[features]
retail_game_testing = []

[dependencies]
crc = "3.0.0"
binrw = "0.9.2"
libz-sys = { version = "1.1.8", default-features = false }
bitfield-struct = "0.1.7"
paste = "1.0.7"
half = "2.1.0"