[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "warn"

[licenses]
unlicensed = "deny"
allow = [
    "Unicode-DFS-2016" # used for unicode-ident
]
copyleft = "allow"
allow-osi-fsf-free = "both"
default = "deny"
confidence-threshold = 0.8

[bans]
multiple-versions = "deny"
wildcards = "warn"
highlight = "all"
skip = [
    # currently ciborium dep from criterion is still dependent on half v1 for some reason. since this is dev dependency, i don't care :-)
    { name = "half", version = "=1.8.2"}
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
