name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  reuse:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v3

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy
    - name: Run deny-check
      run: |
        cargo install --locked cargo-deny
        cargo deny check
    - name: Run semver-checks
      run: |
        cargo install --locked cargo-semver-checks
        cargo semver-checks check-release
